### ISSUE TITLE
Migrate Skill to use Common Play Framework

### ISSUE THREAD

**Issue by rickyphewitt** [rickyphewitt/emby-skill#11]
The Mycroft Team has created a Common Play Framework for skills that use the "play" keyword. 
This helps determine from n number of skills which skills should handle the play request.

See for info: https://mycroft.ai/documentation/skills/common-play-framework/

But need to inhereit from a different base class and impmlement 2ish methods

**Comment by rickyphewitt** [comment]
When the work Emby is in the phrase the confidence level should go up

**Comment by penrods** [comment]
Contact me if you need help with this.  It is really quite easy!

**Comment by rickyphewitt** [comment]
@penrods Thanks for the offer! I have a local branch with most of this done, just havn't found time to finalize it yet. I'm hoping to complete this in the next few weeks.

**Comment by rickyphewitt** [comment]
Done!
