### ISSUE TITLE
Error when trying to play artist

### ISSUE THREAD

**Issue by Ittiz** [rickyphewitt/emby-skill#25]
So this skill doesn't work well for me.  If I tell it to play something nothing happens, no error... nothing.  However if I tell it to play an artist it gives the following error:

""
20:07:34.870 - mycroft.skills.skill_manager:handle_converse_request:498 - ERROR - Error in converse method for skill emby.rickyphewitt
Traceback (most recent call last):
File "/home/xxx/mycroft-core/mycroft/skills/skill_manager.py", line 492, in handle_converse_request
result = instance.converse(utterances, lang)
AttributeError: 'NoneType' object has no attribute 'converse'
""

On a side note if I rewrite the vocab of the skill to be like "emby play song" rather than "play song from emby" it works.

**Comment by rickyphewitt** [comment]
I have not seen this error before and will try to reproduce it. What device are you running this on and how did you install/setup the skill.

I've had trouble with mycroft understanding the word 'emby'. I've had to add mb in the vocab section as you may have noticed. Interesting that the skill is involked when you say emby at the front of the command (after changing the vocab to match)

**Comment by rickyphewitt** [comment]
I did run into an issue where the common play path E.g 'Play foo' was throwing an error, I believe that error was caused by a change in the latest version of mycroft. 

What version of mycroft core are you running. I'm testing on latest 19.02. I'll test on a mark 1 later today.

**Comment by Ittiz** [comment]
at the moment I'm running 18.8.  Just a note if a skill doesn't seem to work I input it directly into the cli to make sure it didn't misunderstand me.   I installed the skill by typing "install emby" into the cli.

 I reinstalled the skill yesterday and now the skill can't connect to the server.  Even though the settings are the same as it was.  It's throws and error:  
Emby - INFO - No connection adapters were found for '127.0.0.1:8096/Users/AuthenticateByName'

A side note I tried this with emby server version 3.5.3.0 and the latest 4.0.2.0.

**Comment by Ittiz** [comment]
Updated Mycroft to the latest too, issue still the same issue.  My system is set up on a Debian based server and not a Mark 1 or Picroft

**Comment by rickyphewitt** [comment]
For the No connection adapters issue; you need to include the http:// or https:// in the hostname. I'll add an issue to detect and default to http:// if no url scheme is set. 

My dev environment is ubuntu with mycroft installed.

**Comment by rickyphewitt** [comment]
@Ittiz,

Did the addition of http/https fix the issue or are you still seeing the original error in the logs?

**Comment by Ittiz** [comment]
After all the updating it seems to be working now.  Thanks

**Comment by rickyphewitt** [comment]
Awesome! if you run into any other issues please let me know :)
