### ISSUE TITLE
settingsmeta error

### ISSUE THREAD

**Issue by krisgesling** [rickyphewitt/emby-skill#43]
Hi there,

It looks like there’s a slight problem with the new settingsmeta file. The contents got changed to YAML formatting, so need to rename that file from `settingsmeta.json` to `settingsmeta.yaml`

Also on line 18 you probably need to remove the slash where it says “Username/password”, maybe replace that with just “and”.

**Comment by rickyphewitt** [comment]
Thanks for catching this! I totally missed that the file was stil .json vs yaml :man_facepalming:
