### ISSUE TITLE
Feature Request: Playlist support

### ISSUE THREAD

**Issue by theidiotyouyellat** [rickyphewitt/emby-skill#48]
First off, thank you for the skill.

It would be nice to be able to play playlists from emby. For example, "play Christmas mix from emby".

**Comment by rickyphewitt** [comment]
I like this idea! I don't really use playlists in Emby very much, but I know playlists are a big part of digital music! Let me see what I can do :)

**Comment by rickyphewitt** [comment]
I've added support for simple playlist functionality. Just Say 'Play playlist {playlistNameHere} from Emby' and if the playlist is found it will play it. This hasn't been merged into the mycroft release yet, so to install you will need to use MSM. 
See: https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/msm
Then its just: msm -l install https://github.com/rickyphewitt/emby-skill

**Comment by theidiotyouyellat** [comment]
Thank you so much this is great!
